In [1]:
#기상자료 수집

In [2]:
import requests
import pandas as pd

In [3]:
url='https://www.weather.go.kr/weather/observation/currentweather.jsp'
res=requests.get(url)
html=res.text

In [4]:
df=pd.read_html(html)
type(df)

list

In [5]:
df

[     지점   날씨                    기온(℃)                강수       바람  \
      지점 현재일기   시정km 운량1/10 중하운량  현재기온 이슬점온도  체감온도 일강수mm 습도%   풍향
 0    강릉  NaN  20 이상    NaN  NaN  24.1  21.2  26.8   5.8  84    서
 1   강진군  NaN   14.0    NaN  NaN  27.0  24.8  30.1   2.5  88  서남서
 2    강화  NaN  20 이상    NaN  NaN  24.7  22.5  27.7  61.9  88    서
 3    거제  NaN    8.9    NaN  NaN  26.0  24.0  29.1   0.1  89  북북서
 4    거창  NaN   17.0    NaN  NaN  27.1  24.7  30.1  34.2  87   남서
 ..  ...  ...    ...    ...  ...   ...   ...   ...   ...  ..  ...
 90   합천   흐림  20 이상   10.0  3.0  28.6  25.8  31.5  11.2  85   남서
 91   해남  NaN   10.9    NaN  NaN  26.1  24.6  29.5   0.9  92   남서
 92   홍성   흐림  20 이상    9.0  4.0  25.0  21.9  27.7  67.6  83  남남서
 93   홍천  NaN  20 이상    NaN  NaN  26.8  21.7  28.9  78.9  74   남서
 94  흑산도   흐림   13.4    9.0  9.0  26.3  25.0  29.7  18.6  93  남남서

                                              기압(hPa)
                      풍속writeWindSpeedUnit();    해면기압
 0   writeWindSpeed('0.5', false, '', '', 1);  1005.7
 1   writeWindSpeed('2.7', false, '', '', 1);  1008.9
 2   writeWindSpeed('3.0', false, '', '', 1);  1006.7
 3   writeWindSpeed('2.2', false, '', '', 1);  1008.6
 4   writeWindSpeed('2.0', false, '', '', 1);  1006.2
 ..                                       ...     ...
 90  writeWindSpeed('1.5', false, '', '', 1);  1007.0
 91  writeWindSpeed('4.6', false, '', '', 1);  1008.5
 92  writeWindSpeed('1.6', false, '', '', 1);  1007.1
 93  writeWindSpeed('2.1', false, '', '', 1);  1005.4
 94  writeWindSpeed('3.1', false, '', '', 1);  1007.7

 [95 rows x 13 columns]]

In [6]:
type(df[0])

pandas.core.frame.DataFrame

In [18]:
url='https://finance.naver.com/item/main.nhn?code=005930'
res=requests.get(url)
html=res.text

In [19]:
df=pd.read_html(html)
df[3]

       주요재무정보    최근 연간 실적                                       최근 분기 실적  \
       주요재무정보     2017.12     2018.12     2019.12  2020.12(E)    2019.03
       주요재무정보      IFRS연결      IFRS연결      IFRS연결      IFRS연결     IFRS연결
0         매출액  2395754.00  2437714.00  2304009.00  2330954.00  523855.00
1        영업이익   536450.00   588867.00   277685.00   325283.00   62333.00
2       당기순이익   421867.00   443449.00   217389.00   248568.00   50436.00
3       영업이익률       22.39       24.16       12.05       13.96      11.90
4        순이익률       17.61       18.19        9.44       10.66       9.63
5   ROE(지배주주)       21.01       19.63        8.69        9.37      16.21
6        부채비율       40.68       36.97       34.12         NaN      36.27
7        당좌비율      181.61      204.12      233.57         NaN     209.25
8         유보율    24536.12    27531.92    28856.02         NaN   27832.98
9      EPS(원)     5421.00     6024.00     3166.00     3627.00     752.00
10     PER(배)        9.40        6.42       17.63       15.69       8.54
11     BPS(원)    30427.00    35342.00    37528.00    39934.00   36142.00
12     PBR(배)        1.67        1.09        1.49        1.42       1.24
13   주당배당금(원)      850.00     1416.00     1416.00     1492.00        NaN
14   시가배당률(%)        1.67        3.66        2.54         NaN        NaN
15    배당성향(%)       14.09       21.92       44.73         NaN        NaN


      2019.06    2019.09    2019.12    2020.03 2020.06(E)
       IFRS연결     IFRS연결     IFRS연결     IFRS연결     IFRS연결
0   561271.00  620035.00  598848.00  553252.00  511401.00
1    65971.00   77779.00   71603.00   64473.00   64703.00
2    51806.00   62877.00   52270.00   48849.00   52746.00
3       11.75      12.54      11.96      11.65      12.65
4        9.23      10.14       8.73       8.83      10.31
5       13.23      10.05       8.69       8.45        NaN
6       33.05      34.14      34.12      34.19        NaN
7      230.74     235.80     233.57     237.80        NaN
8    28129.35   28541.64   28856.02   29134.12        NaN
9      746.00     899.00     770.00     720.00     735.00
10      10.48      13.73      17.63      15.24      72.90
11   36789.00   37600.00   37528.00   38053.00        NaN
12       1.28       1.30       1.49       1.25        NaN
13        NaN        NaN        NaN        NaN        NaN
14        NaN        NaN        NaN        NaN        NaN
15        NaN        NaN        NaN        NaN        NaN